[package]
name    = "hwaddr"
version = "0.1.2"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "MAC address handling."
repository  = "https://github.com/meh/rust-hwaddr"
keywords    = ["address", "mac", "hw", "network"]

[dependencies]
phf = "0.7"
serde = { version = "1.0", optional = true, features = ["derive"] }

[build-dependencies]
reqwest     = "0.6"
url         = "1.4"
regex       = "0.2"
phf_codegen = "0.7"

[features]
database = []
